styling article page
maxmind-zendesk-theme/zendesk-theme pull request #19
Opened 2021-08-06 18:58 UTC by dhogan8

I do have a handful of questions on how we want to style the article page, but here is the draft so far.

2021-08-13 16:27 UTC, christophermluna commented
can we modify the JS so that category classes are added to the <body> element rather than the header?

2021-08-16 12:02 UTC, wesrice requested changes
Looks great. Two small change requests.

2021-08-16 13:12 UTC, dhogan8 commented on src/templates/section_page.hbs
> +    var categoryTitle = document.querySelector('ol.breadcrumbs > li:nth-child(2) > a');
Thanks! I made the requested changes.

2021-08-17 02:21 UTC, wesrice approved these changes

2021-08-17 02:21 UTC, merged