Section page draft
maxmind-zendesk-theme/zendesk-theme pull request #20
Opened 2021-08-17 19:55 UTC by dhogan8

2021-08-18 13:59 UTC, christophermluna commented
I think it looks good. I adjusted the break points for mobile, and the padding on mobile a bit. I'm going to tag Wes and Kevin in to see if they have design feedback.

2021-08-19 14:50 UTC, christophermluna approved these changes

2021-09-02 02:20 UTC, wesrice commented on src/styles/_section.scss
> +      'header ....'
Fwiw, this can be written as:

```css
'header   .'
'articles .';
```

2021-09-02 02:27 UTC, wesrice requested changes
The design looks good. I think there _may_ be some padding / spacing things we can tighten up, but I want to hold off on adjustments until we see how everything holds up with a lot of content populated. Once we see how the content plays with each other, it'll be a lot easier to see how some elements might be too close or too far apart.

2021-09-03 10:08 UTC, wesrice approved these changes

2021-09-03 10:08 UTC, merged