Final tweaks
maxmind-zendesk-theme/zendesk-theme pull request #36
Opened 2021-11-30 17:28 UTC by dhogan8

2021-11-30 17:35 UTC, dhogan8 commented on src/scripts/pages/categories.js
> +    } else if ($categoryTitle.innerText === 'minFraud Web Services') {
I wonder if there is a way to reduce the duplicate code. I tried using or statements such as the following, but it didn't work.

```
else if ($minfraudCategory || $categoryTitle.innerText === 'minFraud Web Services')
```

2021-11-30 17:37 UTC, dhogan8 commented on src/scripts/pages/sidebar.js
> +window.addEventListener('DOMContentLoaded', () => {
We might want to consider either combining this with `categories.js` or renaming both files (`sidebar.js` or `categories.js`) to better depict what the files are doing. They both touch the same part of the UI, which is why I think they could be in the same file, but they do slightly different things.

2021-12-06 15:01 UTC, wesrice requested changes
Looks good! I have a few points of feedback.

2021-12-06 22:18 UTC, wesrice approved these changes

2021-12-06 22:19 UTC, merged